apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: account-ms-db
  name: account-ms-db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-ms-db
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: account-ms-db
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              key: DB_NAME
              name: mysql-config
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              key: DB_USER
              name: mysql-config
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: DB_PASSWORD
              name: mysql-config
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: DB_ROOT_PASSWORD
              name: mysql-config        
        image: mysql:5.7
        imagePullPolicy: IfNotPresent
        name: mysql