apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: account-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-ms
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: account-ms
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              key: SPRING_PROFILES_ACTIVE
              name: app-config
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://account-ms-db-service:3306/mysqldb
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              key: SPRING_DATASOURCE_USERNAME
              name: app-config
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: SPRING_DATASOURCE_PASSWORD
              name: app-config
        image: cgibdemo.azurecr.io/accountservice:latest
        imagePullPolicy: Always
        name: accountservice